project:
  type: website
  output-dir: docs

title: Global Passport Strengths
subtitle: STA/ISS 313L - Spring 2026 - Project 1 
author: Naya Ko, N'Avea Saint Louis, Alain Fornes, Tuna Korkmaz
bibliography: references.bib

website:
  navbar:
    right:
      - icon: github
        href: https://github.com/vizdata-s26/project-1
    left:
      - text: Project
        href: index.qmd
      - text: Presentation
        href: presentation.qmd
      - href: proposal.qmd
      - href: about.qmd

format:
  html:
    toc: true

out-width: "70%"
fig-retina: 3 
fig-dpi: 300 
fig-width: 8 
fig-asp: 0.618 
