on:
  push:
    branches: main
  workflow_dispatch:

name: Render website

jobs:
  build-website:
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - name: Install packages
        run: |
          pak::pak(setdiff(unique(pak::scan_deps()$package), checklist::installed_pkgs()))
        shell: Rscript {0}
        
      - name: Render Quarto Project
        run: |
          quarto render &&
          touch docs/.nojekyll
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: false
          branch: gh-pages
          folder: docs
